### ISSUE TITLE
File linking in Python course

### ISSUE THREAD

**Issue by mvanrongen** [cambiotraining/software-installation#1]
Paul J: If your participants follow the windows instructions you've given they'll end up with a mamba environment within a windows based system as such you might find some of the "files" section needs adjusting for as I think it relies on linux file seperators and the "cat" command

**Comment by tavareshugo** [comment]
@cambioinfo I've checked this on my Windows installation of JupyterLab. The file paths work fine with `/`. And the `cat` command also works on the windows terminal that opens by default with JupyterLab (Powershell seems to open by default). In any case, if it doesn't work, people can simply double-click the file to open it.
